# map
roads = [
    [[300, 98], [160, 98]],     # 0
    [[160, 98], [0, 98]],       # 1
    [[0, 102], [160, 102]],     # 2
    [[160, 102], [300, 102]],   # 3
    [[180, 60], [0, 60]],       # 4
    [[220, 55], [180, 60]],     # 5
    [[300, 30], [220, 55]],     # 6
    [[180, 60], [160, 98]],     # 7
    [[158, 130], [300, 130]],   # 8
    [[0, 178], [155, 178]],     # 9
    [[155, 178], [300, 178]],   # 10
    [[300, 182], [155, 182]],   # 11
    [[155, 182], [0, 182]],     # 12
    [[160, 102], [158, 130]],   # 13
    [[158, 130], [155, 180]]    # 14
    ]

legal_routes = [
    [0, 1],
    [2, 3], [2, 13, 8], [2, 13, 14, 10], [2, 13, 14, 12]
]


# generation
stochastic = true